name: CI

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: update
        run: node scripts/i-am-still-alive.js 
        
      - name: commit
        run: |
          git config --global user.email zhaodonghao586@outlook.com
          git config --global user.name robot
          git add .
          git commit -m "chore: i am still alive" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
